apiVersion: v1
kind: Pod
metadata:
  name: insecure-pod
  labels:
    app: insecure-app
spec:
  containers:
  - name: insecure-container
    image: nginx:latest
    ports:
    - containerPort: 80
    securityContext:
      privileged: true
      runAsUser: 0
      allowPrivilegeEscalation: true
      capabilities:
        add:
        - SYS_ADMIN
        - NET_ADMIN
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    env:
    - name: SECRET_KEY
      value: "super-secret-key-123"
    - name: DATABASE_PASSWORD
      value: "password123"
  hostNetwork: true
  hostPID: true
  restartPolicy: Always
